### PR TITLE
Add `EnableMultipleHttp2Connections` property to `HttpHandlerOptions`

### PR DESCRIPTION
**Pull request by EngRajabi**
If you activate HTTP/2, it is better to activate the `SocketsHttpHandler.EnableMultipleHttp2Connections` configuration as well, which gives good results. 

## Docs
- [What is HTTP/2 multiplexing?](https://medium.com/@neelendra1destiny/what-is-http-2-multiplexing-72a400cd33b7)
- [MS Learn | .NET | SocketsHttpHandler.EnableMultipleHttp2Connections Property](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.enablemultiplehttp2connections?view=net-8.0)

### CODE REVIEW

**Comment by raman-m** [comment]
Thank you, Mohsen!
Is prioritization required for this PR?
It seems straightforward, and we could aim to deliver it in the release following the [23.3 Hotfixes](https://github.com/ThreeMammals/Ocelot/milestone/8).

**Comment by EngRajabi** [comment]
> Thank you, Mohsen! Is prioritization required for this PR? It seems straightforward, and we could aim to deliver it in the release following the [23.3 Hotfixes](https://github.com/ThreeMammals/Ocelot/milestone/8).
> 
> Currently, there is a shortage of both unit and acceptance tests to begin the review process. We need to implement a genuine HTTP/2 + The Option acceptance test to assess the stability of Ocelot Core in this scenario.

It is not a high priority.
I can get a load test for it. But it is time consuming

File: docs/features/configuration.rst [hunk 1]
```diff
@@ -238,7 +238,8 @@ Use ``HttpHandlerOptions`` in a Route configuration to set up ``HttpHandler`` be
     "AllowAutoRedirect": false,
     "UseCookieContainer": false,
     "UseTracing": true,
-    "MaxConnectionsPerServer": 100
+    "MaxConnectionsPerServer": 100,
+    "EnableMultipleHttp2Connections": false
```
Comment (raman-m) [inline docs/features/configuration.rst:242]: Props should be sorted in docs code snippet.

File: docs/features/configuration.rst [hunk 2]
```diff
@@ -394,7 +398,10 @@ HTTP/2 version policy
     "DownstreamScheme": "https",
     "DownstreamHttpVersion": "2.0",
     "DownstreamHttpVersionPolicy": "", // empty
-    "DangerousAcceptAnyServerCertificateValidator": true
+    "DangerousAcceptAnyServerCertificateValidator": true,
+    "HttpHandlerOptions":{
+        "EnableMultipleHttp2Connections": true
```
Comment (raman-m) [inline docs/features/configuration.rst:403]: Is it required?
@ibnuda Have you faced with the same problem when the property must be enabled for HTTP/2?

**Review by raman-m — COMMENTED** [review]
My suggestions are below 👇

File: docs/features/configuration.rst (hunk 2 above)
Comment (ibnuda) [reply docs/features/configuration.rst:403]: hi @raman-m to be honest, i haven't faced the same problem. but if microsoft recommends it, then i think it's better to enable it

Comment (raman-m) [reply docs/features/configuration.rst:403]: It appears that all properties of the .NET `SocketsHttpHandler` class ought to be included in Ocelot's `HttpHandlerOptions` class. Currently, the implemented functionality is quite limited, and ideally, Ocelot would offer settings for every `SocketsHttpHandler` property. Indeed, this presents a significant design challenge. 🤔

Comment (raman-m) [reply docs/features/configuration.rst:403]: ### TODO
- [ ] Create a milestone to implement most of the .NET `SocketsHttpHandler` properties through the `HttpHandlerOptions` class

File: src/Ocelot/Configuration/HttpHandlerOptions.cs [hunk 3]
```diff
@@ -51,5 +52,11 @@ public HttpHandlerOptions(bool allowAutoRedirect, bool useCookieContainer, bool
         /// </summary>
         /// <value>PooledConnectionLifeTime.</value>
         public TimeSpan PooledConnectionLifeTime { get; }
+
+        /// <summary>
+        /// Gets or sets a value that indicates whether additional HTTP/2 connections can be established to the same server.
+        /// </summary>
+        /// <value>EnableMultipleHttp2Connections.</value>
+        public bool EnableMultipleHttp2Connections { get; set; }
```
Comment (RaynaldM) [inline src/Ocelot/Configuration/HttpHandlerOptions.cs:60]:
```suggestion
        public bool EnableMultipleHttp2Connections { get; }

```

**Review by RaynaldM — APPROVED** [review]

**Review by RaynaldM — APPROVED** [review]

**Comment by raman-m** [comment]
### TODO
- [ ] Fix code review issues
- [ ] Add unit tests
- [ ] Add acceptance tests

**Review by raman-m — CHANGES_REQUESTED** [review]
### TODO
- [ ] Fix code review issues
- [ ] Add unit tests
- [ ] Add acceptance tests

File: docs/features/configuration.rst (hunk 2 above)
Comment (EngRajabi) [reply docs/features/configuration.rst:403]: @raman-m 
Do you mean to add all the fields?

Comment (raman-m) [reply docs/features/configuration.rst:403]: @EngRajabi Sorry! This is my personal project managing TODO. Please ignore it!
Why not to focus on code review issues and [requested tests](https://github.com/ThreeMammals/Ocelot/pull/2126#pullrequestreview-2271925686)?

File: src/Ocelot/Configuration/Creator/HttpHandlerOptionsCreator.cs [hunk 4]
```diff
@@ -25,7 +25,8 @@ public HttpHandlerOptions Create(FileHttpHandlerOptions options)
             var pooledConnectionLifetime = TimeSpan.FromSeconds(options.PooledConnectionLifetimeSeconds ?? DefaultPooledConnectionLifetimeSeconds);
 
             return new HttpHandlerOptions(options.AllowAutoRedirect,
-                options.UseCookieContainer, useTracing, options.UseProxy, maxConnectionPerServer, pooledConnectionLifetime);
+                options.UseCookieContainer, useTracing, options.UseProxy, maxConnectionPerServer, pooledConnectionLifetime,
+                options.EnableMultipleHttp2Connections);
```
[the remark this answers is not in the document]
Comment (EngRajabi) [reply src/Ocelot/Configuration/Creator/HttpHandlerOptionsCreator.cs:29]: @raman-m 
How to transfer the conditions of lines 21, 24 and 25? Line 21 uses ITracer

File: test/Ocelot.UnitTests/Configuration/HttpHandlerOptionsCreatorTests.cs [hunk 5]
```diff
@@ -178,7 +178,26 @@ public void should_create_options_fixing_specified_MaxConnectionsPerServer_range
...
-            var expectedOptions = new HttpHandlerOptions(false, false, false, true, int.MaxValue, DefaultPooledConnectionLifeTime);
+            var expectedOptions = new HttpHandlerOptions(false, false, false, true, int.MaxValue, DefaultPooledConnectionLifeTime, false);
+
+            this.Given(x => GivenTheFollowing(fileRoute))
+                .When(x => WhenICreateHttpHandlerOptions())
+                .Then(x => ThenTheFollowingOptionsReturned(expectedOptions))
+                .BDDfy();
+        }
+
+        [Fact]
```
[the remark this answers is not in the document]
Comment (EngRajabi) [reply test/Ocelot.UnitTests/Configuration/HttpHandlerOptionsCreatorTests.cs:189]: I did not understand what you mean

[the remark this answers is not in the document]
Comment (raman-m) [reply test/Ocelot.UnitTests/Configuration/HttpHandlerOptionsCreatorTests.cs:189]: I mean this
https://github.com/ThreeMammals/Ocelot/blob/ce0227c059f220761acc2d880e554174bdb3c544/test/Ocelot.UnitTests/Requester/MessageInvokerPoolTests.cs#L131

**Comment by raman-m** [comment]
@RaynaldM, why did you approve the PR? It lacks new unit tests and doesn't include any acceptance tests. Additionally, the issues I raised during the code review remain unaddressed.
Does your approval indicate that your suggestions have been implemented and you do not plan to review or enhance it further? Is that the reason for your approval?

**Comment by RaynaldM** [comment]
@raman-m I don't materially have the time to explore the PRs in depth, I'm content with a surface review, more on form than substance, and so my approval is on form.

**Comment by raman-m** [comment]
Mohsen,  
The merge from develop not handled correctly!
Could you please resolve the conflicts carefully to ensure a green build, free from compilation errors?

**Comment by EngRajabi** [comment]
> @EngRajabi Dear author, Please address the compilation, as the build has failed for the last two commits. Specifically, the most recent merge from the develop branch was unsuccessful.
> 
> > This is the second notification from our team: you have been issued a yellow card 🟨
> > If further instances of pushing bad commits (broken code) occur, you may receive a red card.

Hello dear friend. You have kept this merge so long that it is outdated. I don't have time to correct the changes.
